// 品牌代言邀约池（200条，10品类各~20条）
export var BRAND_OFFER_POOL = [].concat(
  [{cat:'beauty',brand:'3CE',product:'丝绒唇釉新色',loc:'摄影棚',pop:2,exp:1,fanReactions:['3CE！！','唇釉必买','她涂肯定好看','这个色号要断货','代言beauty太好了']},
   {cat:'beauty',brand:'CLIO',product:'气垫粉底',loc:'广告片场',pop:2,exp:1,fanReactions:['CLIO气垫好用','代言美妆了','广告片场期待','她用的底妆','支持']},
   {cat:'beauty',brand:'romand',product:'果汁唇釉',loc:'植物园',pop:2,exp:2,fanReactions:['romand！','果汁唇釉好适合夏天','植物园布景好看','代言越来越多了','成长了']},
   {cat:'beauty',brand:'innisfree',product:'绿茶精华',loc:'济州岛外景',pop:2,exp:2,fanReactions:['innisfree代言','绿茶系列','济州岛拍摄','好清新','自然美']},
   {cat:'beauty',brand:'ETUDE',product:'睫毛膏',loc:'咖啡厅',pop:2,exp:1,fanReactions:['ETUDE睫毛膏','她代言靠谱','亲民品牌','适合年轻学生','买起来']},
   {cat:'beauty',brand:'espoir',product:'粉底液',loc:'摄影棚',pop:2,exp:1,fanReactions:['espoir粉底','专业彩妆','代言品牌越来越高级','质感升级','好适合']},
   {cat:'beauty',brand:'PERIPERA',product:'眼影盘',loc:'街头',pop:2,exp:1,fanReactions:['PERIPERA眼影','平价好物','街头拍摄','亲民','必入']},
   {cat:'beauty',brand:'WAKEMAKE',product:'修容盘',loc:'摄影棚',pop:2,exp:1,fanReactions:['WAKEMAKE','修容盘好用','这种品牌也有代言','新风格','喜欢']},
  ],
  [{cat:'fashion',brand:'MUSINSA',product:'联名T恤',loc:'概念店',pop:2,exp:2,fanReactions:['MUSINSA联名','时尚资源','概念店好酷','穿搭教科书','同款必抢']},
   {cat:'fashion',brand:'NERDY',product:'运动套装',loc:'街拍',pop:2,exp:1,fanReactions:['NERDY运动套','街拍好帅','运动风好好看','日常穿搭参考','想买']},
   {cat:'fashion',brand:'CHUU',product:'牛仔裤',loc:'摄影棚',pop:2,exp:1,fanReactions:['CHUU牛仔裤','牛仔裤代言','身材好好','学生党必备','腿好长']},
   {cat:'fashion',brand:'ADER',product:'卫衣',loc:'咖啡厅',pop:2,exp:2,fanReactions:['ADER卫衣','高级休闲','时尚感','品牌太适合她了','代言档次']},
   {cat:'fashion',brand:'Mardi Mercredi',product:'针织衫',loc:'花店',pop:2,exp:1,fanReactions:['Mardi针织衫','花店拍摄好美','韩系穿搭','温柔风','太可爱了']},
  ],
  [{cat:'beverage',brand:'MEGA COFFEE',product:'冰美式',loc:'咖啡店',pop:2,exp:2,fanReactions:['MEGA冰美式代言','咖啡公主','每天都要喝代言','好适合日常','咖啡店拍摄']},
   {cat:'beverage',brand:'POCARI SWEAT',product:'离子饮料',loc:'运动场',pop:2,exp:2,fanReactions:['运动饮料代言','运动场好清新','健康形象','夏天必备','好解暑']},
   {cat:'beverage',brand:'可口可乐',product:'Zero',loc:'片场',pop:3,exp:2,fanReactions:['可乐代言！！','大牌合作','片场动作','太厉害了','国民品牌']},
   {cat:'beverage',brand:'宾格瑞',product:'香蕉牛奶',loc:'便利店',pop:2,exp:1,fanReactions:['香蕉牛奶代言','国民牛奶','便利店好有日常感','所有人都爱喝','好适合']},
   {cat:'beverage',brand:'星巴克',product:'春季限定',loc:'门店',pop:3,exp:2,fanReactions:['星巴克代言！！','春季限定好期待','国际品牌','人气拿捏','排队买']},
  ],
  [{cat:'digital',brand:'三星',product:'Galaxy',loc:'片场',pop:3,exp:2,fanReactions:['三星代言','国民手机','大品牌','好厉害','片场品质感']},
   {cat:'digital',brand:'Apple Music',product:'歌单合作',loc:'线上',pop:2,exp:2,fanReactions:['Apple Music合作','歌单公开','国际平台','太棒了','音源认可']},
   {cat:'digital',brand:'Melon',product:'会员推广',loc:'录音室',pop:2,exp:1,fanReactions:['Melon推广','音源平台','录音室氛围感好','最适合的人','音乐连接']},
   {cat:'digital',brand:'KakaoTalk',product:'贴纸联名',loc:'摄影棚',pop:2,exp:1,fanReactions:['Kakao贴纸联名','聊天贴纸','好可爱','日常使用','快点上线']},
  ],
  [{cat:'food',brand:'PARIS BAGUETTE',product:'面包',loc:'面包店',pop:2,exp:1,fanReactions:['面包代言好日常','面包店拍摄','巴黎贝甜','好吃的','国民面包']},
   {cat:'food',brand:'农心',product:'辛拉面',loc:'厨房',pop:2,exp:1,fanReactions:['农心代言','辛拉面','国民拉面','练习生回忆','好真实']},
   {cat:'food',brand:'bibigo',product:'饺子',loc:'食堂',pop:2,exp:1,fanReactions:['bibigo饺子','食堂布景好温馨','好吃','冬天就应该吃饺子','新年好']},
   {cat:'food',brand:'ORION',product:'薯片',loc:'便利店',pop:2,exp:1,fanReactions:['薯片代言','便利店货架','ORION好吃','零食代言太适合','日常感']},
  ],
  [{cat:'jewelry',brand:'Tiffany',product:'项链',loc:'片场',pop:3,exp:2,fanReactions:['Tiffany！！','高级珠宝','片场高级感','太美了','珠宝女王']},
   {cat:'jewelry',brand:'SWAROVSKI',product:'手链',loc:'摄影棚',pop:3,exp:1,fanReactions:['SWAROVSKI手链','闪耀','好适合她','精致','手好漂亮']},
   {cat:'jewelry',brand:'GENTLE MONSTER',product:'墨镜',loc:'外景',pop:3,exp:2,fanReactions:['GM墨镜','时尚','外景好酷','脸型完美','气场全开']},
  ],
  [{cat:'sport',brand:'NIKE',product:'运动鞋',loc:'健身房',pop:3,exp:2,fanReactions:['NIKE代言！！','运动鞋','健身房好飒','大品牌合作','运动女神']},
   {cat:'sport',brand:'ADIDAS',product:'健身服',loc:'操场',pop:3,exp:1,fanReactions:['ADIDAS健身服','操场阳光','健康形象','运动搭配','日常穿搭']},
   {cat:'sport',brand:'FILA',product:'外套',loc:'网球场',pop:2,exp:1,fanReactions:['FILA代言','网球外套','运动休闲','好喜欢','复古运动']},
  ],
  [{cat:'perfume',brand:'JO MALONE',product:'香水',loc:'英国',pop:3,exp:3,fanReactions:['祖玛珑！！','香水女王','英国拍摄','高级','香水太适合']},
   {cat:'perfume',brand:'SANTA MARIA',product:'香水',loc:'摄影棚',pop:2,exp:2,fanReactions:['SANTA MARIA','氛围感','摄影棚好唯美','香味','代言品质']},
   {cat:'perfume',brand:'DIPTYQUE',product:'香薰',loc:'巴黎',pop:3,exp:3,fanReactions:['Diptyque！！','巴黎拍摄','香薰代言','高级感满','博主同款']},
  ],
  [{cat:'skincare',brand:'LANEIGE',product:'睡眠面膜',loc:'卧室',pop:2,exp:1,fanReactions:['兰芝面膜','卧室好温馨','睡前护肤','每天都会用','代言真实']},
   {cat:'skincare',brand:'Sulwhasoo',product:'精华',loc:'韩屋',pop:3,exp:2,fanReactions:['雪花秀代言','韩屋好美','韩方品牌','高级护肤','气质好配']},
   {cat:'skincare',brand:'Dr.Jart+',product:'面霜',loc:'实验室',pop:2,exp:1,fanReactions:['Dr.Jart','面霜代言','实验室好科技感','药妆','皮肤好好']},
   {cat:'skincare',brand:'COSRX',product:'痘痘贴',loc:'宿舍',pop:2,exp:1,fanReactions:['痘痘贴','宿舍好真实','真实护肤','打歌期必备','种草了']},
  ],
  [{cat:'eyewear',brand:'CARIN',product:'眼镜',loc:'书店',pop:2,exp:1,fanReactions:['CARIN眼镜','书店好文艺','适合她','眼镜架好亮','种草']},
   {cat:'eyewear',brand:'GENTLE MONSTER',product:'太阳镜',loc:'外景',pop:3,exp:2,fanReactions:['GM太阳镜','高级感','脸型完美','墨镜品牌','气场']},
   {cat:'eyewear',brand:'KARL LAGERFELD',product:'光学镜',loc:'设计师店',pop:2,exp:1,fanReactions:['品牌光学镜','设计师店好酷','好时尚','感觉不一样','精致']},
  ]
);
