// Dispatch 八卦新闻池（200条，扁平单层数组）
export var DISPATCH_POOL = [].concat([
  {t:'Dispatch独家：新人女团{groupName}与SEVENTEEN疑似同车离开——凌晨两点，仁川方向。',exposure:4,fanReactions:['Dispatch又来了','同车而已','凌晨有行程很正常','保护隐私','不要看图编故事']},
  {t:'Dispatch实锤：某女团成员穿同款卫衣——是巧合还是情侣装？',exposure:3,fanReactions:['衣服同款而已','情侣装过度解读','可能只是巧合','衣服一样就提','品牌赞助']},
  {t:'Dispatch独家直击——{name}深夜独自在天台徘徊，公司人士称她最近承受很大压力。',exposure:2,fanReactions:['一个人待着都成新闻','一定很累吧','保护艺人隐私','给她喘息的空间','不要拍天台']},
  {t:'Dispatch曝光：{name}手机屏疑似出现某男团成员自拍——粉丝放大发现只是练习室合影背景。',exposure:2,fanReactions:['练习室背景而已','不要放大看','只是合影','又是Dispatch','手机屏还看']},
  {t:'Dispatch目击：{name}与{maleLead}共同出入同一栋大楼——经纪公司称是工作。',exposure:3,fanReactions:['工作而已','同一栋楼','就是同公司','别大惊小怪','经纪公司澄清']},
  {t:'Dispatch偷拍：{name}练习室深夜灯光——凌晨三点还在练习。',exposure:1,fanReactions:['凌晨练习','好辛苦','Dispatch不用休息吗','练习室都要拍','太努力了']},
  {t:'Dispatch解析：{name}和{maleLead}的关系——七个细节让你看清真相。',exposure:3,fanReactions:['七个细节','又想炒作了','没东西写了','看图编故事','不买账']},
  {t:'Dispatch实锤：{name}与某男团成员共用练习室——同一扇镜子，不同时间。',exposure:2,fanReactions:['练习室共用','不同时间','就是排练','同公司正常','太无聊了']},
  {t:'Dispatch深扒：{name}出道前的素颜照——与现在差别不大，但粉丝反应意外。',exposure:2,fanReactions:['素颜也好美','差别又不大','不要扒出道前','那个时候也好可爱','保护旧照']},
  {t:'Dispatch独家：{name}使用私人号码与{maleLead}通话——时长约12分钟。',exposure:4,fanReactions:['私人号码','通话内容谁透露的','隐私泄露太过分','Dispatch违法了','这是私生活']},
  {t:'Dispatch拍到{maleLead}深夜独自前往{name}所在小区——车内独自沉思约二十分钟后离开。',exposure:3,fanReactions:['独自沉思','什么都没有','就算是误会','Dispatch看太多','小区而已']},
  {t:'Dispatch年度总结：今年最受关注的十对"疑似情侣"——{name}和{maleLead}排第三。',exposure:2,fanReactions:['年度总结还来','只是排行','又是疑似的','没实锤','娱乐新闻罢了']},
  {t:'Dispatch拍到{name}在便利店买夜宵——独自一人。但买了两人份。',exposure:3,fanReactions:['便利店夜宵','两人份','可能给队友','另一份给谁','不要乱猜']},
  {t:'Dispatch独家：{name}更换手机号——旧号疑似频繁被骚扰。粉丝呼吁"给艺人空间"。',exposure:1,fanReactions:['换号好可怜','别骚扰了','给艺人空间','支持换号','保护隐私']},
  {t:'Dispatch曝光：{name}和一群好友聚餐——其中包含多位圈内人士。标题却说"与神秘男子"。',exposure:1,fanReactions:['一群好友','标题又故弄玄虚','其中多位女生','就是个聚餐','神秘男子】']},
  {t:'Dispatch直击——{name}在待机室窗外站立片刻，被队友拉回室内。公司称是透气。',exposure:1,fanReactions:['透气而已','不要放大看','在待机室很正常','被队友拉回好暖','Dispatch太多事了']},
  {t:'Dispatch分析：{name}和{maleLead}的SNS互动频率——三个月内数字触目惊心。',exposure:2,fanReactions:['互动频率','SNS就是正常','三个月而已','什么都数','别算了']},
  {t:'Dispatch特辑：{name}出道以来的绯闻对象——里面列了五六位不同圈内人。',exposure:2,fanReactions:['五六位都在编','出道以来的都算','都是工作上的','狗仔良心呢','不信']},
  {t:'Dispatch直击——{name}和{maleLead}在某颁奖礼后台擦肩而过时交换了一个眼神。时长不到一秒。但被拍成了连拍。',exposure:2,fanReactions:['不到一秒的眼神','擦肩而过','连拍十几张','Dispatch显微镜','过度解读']},
  {t:'Dispatch独家：{name}练习室自拍背景中出现男性背影——被扒出是{maleLead}的造型师。',exposure:1,fanReactions:['造型师而已','练习室很正常','不是他本人','Dispatch失望了','继续挖']},
  {t:'Dispatch拍到{name}独自在汉江边散步——边走边唱。不是工作——是下班后的日常。',exposure:1,fanReactions:['汉江散步','边走边唱','下班日常','这个也要拍','让她一个人待着吧']},
  {t:'Dispatch爆料：{name}更换了私人车辆——贴膜加深至完全看不到内部。网友猜测是为了藏人。',exposure:2,fanReactions:['贴膜加深','防晒不行吗','猜在藏人','只是想要隐私','过度解读']},
  {t:'Dispatch分析{name}和{maleLead}的社交动态——在对方发帖后你这条发疯的间隙只有83秒。意义不明。但Dispatch结论是"暗号"。',exposure:2,fanReactions:['83秒间隔','意义不明','Dispatch说是暗号','巧合还是暗号','太能编了']},
  {t:'Dispatch深夜追踪——{name}和{maleLead}同一天凌晨出现在两个不同的便利店。不同地点但买了同一款泡面。',exposure:2,fanReactions:['不同便利店','同一款泡面','这也能说','就是爱吃泡面','Dispatch缺乏素材']},
  {t:'Dispatch发现{name}和{maleLead}的手机壳是一个牌子——不是同款，是同一家工厂。Dispatch写了整版专题。',exposure:1,fanReactions:['同一家工厂','手机壳话题','这也要写','太无聊了','Dispatch没新闻了']},
  {t:'Dispatch拍到{name}在某大楼地下车库等待——时间十七分钟。后{maleLead}的车从同一车库驶出。公司称是行程重叠。',exposure:3,fanReactions:['地下车库','17分钟','行程重叠','同一栋楼正常','别拍了']},
  {t:'Dispatch深扒：{name}和{maleLead}的共同好友——包括三名以上圈内人士。Dispatch称"两人通过好友圈频繁交集"。',exposure:2,fanReactions:['共用好友','圈内好友','正常社交','Dispatch又来','不是新闻']},
  {t:'Dispatch拍到你从药店出来——拎着一个袋子。不是化妆——是药。第二天你的经纪公司发声明说你只是感冒。Dispatch在下面挂了一天——直到你泡泡发了一张正在喝药的自拍。',exposure:1,fanReactions:['药店出来','只是感冒','泡泡发喝药自拍','这种新闻也要上','都是关心']},
  {t:'Dispatch爆料：{name}和{maleLead}去年同一天在同一座城市——航班时间差34分钟。Dispatch用了5页来做"重合分析"。',exposure:2,fanReactions:['34分钟差','5页分析','Dispatch疯了','航班重合','这也能编']},
  {t:'Dispatch拍到{name}在工作结束后独自去了一家鸡爪店——一个人吃完了一份。Dispatch标题是"独自用餐——是否有心事？"',exposure:1,fanReactions:['鸡爪店','独自用餐','就是饿了她','有心事=饿了','Dispatch太闲']},
  {t:'Dispatch独家：{name}的经纪人深夜出现在{maleLead}所属公司楼下。公司回应只是交接文件。Dispatch不信。',exposure:3,fanReactions:['经纪人出现','交接文件','正常业务','Dispatch不信是Dispatch的事','事实不怕']},
  {t:'Dispatch在机场拍到{name}从到达口出来后看了一眼手机——嘴角微微上扬。Dispatch说"这是收到某人消息的表情。"',exposure:1,fanReactions:['嘴角上扬','看一眼手机','可能就是好笑','Dispatch过于敏感','每个人都会笑']},
  {t:'Dispatch爆料{maleLead}的鞋子品牌和{name}最近机场造型穿的是同系列——不同颜色但同个设计师。',exposure:1,fanReactions:['同个设计师','不同颜色','同系列很常见','果然Dispatch','拜托别算了']},
  {t:'Dispatch拍到在一次活动散场后{name}和{maleLead}在同一个出口——隔着车流。但镜头捕捉到双方同时转头的瞬间。',exposure:2,fanReactions:['同个出口','同时转头','隔着车流','就那么巧','Dispatch捕捉到也不错']},
  {t:'Dispatch年度总结：{name}成为这一年来被提及次数最多的女偶像——不是因为作品——是绯闻。你在采访里说:"我也想因为作品——但这件事不是我能控制的。"',exposure:2,fanReactions:['被提及最多','不是作品是绯闻','不能控制','心疼','希望明年因为作品']},
  {t:'Dispatch独家揭露{name}的行程表与{maleLead}高度重合的巧合。公司出面:"行程都是提前安排的——不存在故意重叠。"',exposure:2,fanReactions:['行程重合','公司澄清','提前安排','正常','Dispatch别找了']},
  {t:'Dispatch拍到{maleLead}在待机室外面走廊上——经过{name}的门时放慢了一步。一步。但Dispatch捕捉到了。',exposure:2,fanReactions:['经过放慢一步','Dispatch捕捉','一步而已','可能就是累了','太细节了']},
  {t:'Dispatch深挖：{name}和{maleLead}多年前在同一个综艺后台的合照被翻出——那时候两人都还没出道。Dispatch写:"命运——从那时就开始了。"但粉丝提醒：那是公司公开的练习生大合照。',exposure:1,fanReactions:['练习生合照','命运从那时','还没出道','公司公开合照','Dispatch借素材']},
  {t:'Dispatch拍到{name}在某咖啡店坐了一下午——一直在本子上写字。Dispatch猜是写给{maleLead}的诗。你后来在泡泡说:"是在写歌词——但不是给他的——是给下一张专辑。"',exposure:1,fanReactions:['咖啡店写字','Dispatch猜是诗','不是给他的','是歌词','Dispatch被打脸']},
  {t:'Dispatch爆料：{name}最近听的Spotify歌单里出现了{maleLead}的歌——被她放在了第一首。Dispatch标题:"歌单的前面——是你的名字。"',exposure:2,fanReactions:['Spotify歌单','他的歌在第一首','Dispatch标题会写','只是听歌','不稀奇']},
  {t:'Dispatch拍到{name}和{maleLead}在不同时间去了同一家健身房——同一台跑步机。Dispatch做了个表格——时间差2小时14分钟。',exposure:2,fanReactions:['同台跑步机','时间差两小时','就是健身房','不一定是同一台','Dispatch算分秒']},
  {t:'Dispatch总结{name}今年所有被拍到的照片——发现她每次被拍都在一个人走。标题:"被追得最紧的人——走得最孤独。"这条意外引发了粉丝对私生饭的集体声讨。',exposure:1,fanReactions:['被追最紧的人','走得最孤独','私生饭声讨','Dispatch自省','难得良心']},
  {t:'Dispatch放出{maleLead}练习室窗外的长焦偷拍——标题是"他在看谁"。但照片里他只是在看手机。画面另一角——是另一个练习室的窗户。里面是另一组人。Dispatch说那组里有{name}。但太模糊了——连男女都看不清。',exposure:3,fanReactions:['长焦偷拍','Dispatch说在看你','太模糊看不清','侵犯隐私','求放过']},
  {t:'Dispatch目击{name}一个人去电影院——买了一人的票。Dispatch却配文:"是不是有人迟到了。"',exposure:1,fanReactions:['一个人看电影','Dispatch说有迟到','就是一个人','不要编','让她自在']},
  {t:'Dispatch跟进报道{name}和{maleLead}——称两人已多次同天出现在同一城市。并附上七个城市的地图和日期。其中三个是打歌行程重合。',exposure:2,fanReactions:['七个城市同天','三个是打歌','行程重合正常','Dispatch认真','但误差大']},
  {t:'Dispatch拍到{name}深夜从公司大楼走出——时间凌晨两点。没有车——她自己叫了出租。Dispatch写了"她大半夜一个人回家——身边没有别人。"这句话下面的热评:"辛苦了。快回家吧。"',exposure:1,fanReactions:['凌晨两点','自己叫出租','身边没人','辛苦了回家','最好的Dispatch头条']},
  {t:'Dispatch旧图新发——三年前{name}和{maleLead}在同一个综艺后台的候场照被翻出来重新发了。标题:"那些被我们错过的时间线——现在补回来了。"',exposure:2,fanReactions:['三年前旧图','重新发','被错过的时间线','Dispatch考古','图片都能翻']},
  // P2 #7: D社元旦爆料特辑
  {t:'D社2026元旦惯例爆料——{name}与{maleLead}的亲密照被公开了。Dispatch配文:"新年礼物——请收下。"网友全疯了。',exposure:8, require:'popularity>=35' },
  {t:'Dispatch年度盘点——"今年被拍到最多次的疑似情侣TOP 3"。你排第一。Dispatch写了:"她今年被拍到十七次——不是运气。是挡不住的命中注定。"',exposure:5, require:'popularity>=30' },
]);
