// 女团英文名池（60条，含粉丝名配对）
// 韩国K-pop风格，简洁有力易记
export var GROUP_NAMES = [
  { group:'ECLIPSE', fandom:'LUMIS' },
  { group:'VELVET MOON', fandom:'VELVETS' },
  { group:'CRYSTAL WAVE', fandom:'AURORAS' },
  { group:'NEON RUSH', fandom:'NEONS' },
  { group:'MIDNIGHT LACE', fandom:'VEILS' },
  { group:'ROSÉ QUARTZ', fandom:'ROSÉS' },
  { group:'SILVER SPHERE', fandom:'SPHERES' },
  { group:'PIXEL DREAM', fandom:'PIXELS' },
  { group:'CHERRY BULLET', fandom:'CHERRIES' },
  { group:'AURORA WAVE', fandom:'WAVES' },
  { group:'STARLIT', fandom:'STARLIGHTS' },
  { group:'BLUE OCEAN', fandom:'TIDES' },
  { group:'SUGAR RUSH', fandom:'SWEETS' },
  { group:'BLACK PEARL', fandom:'PEARLS' },
  { group:'IVORY', fandom:'IVORIES' },
  { group:'MOON CHILD', fandom:'LUNARS' },
  { group:'GLOSS', fandom:'GLOSSY' },
  { group:'RUBY HEART', fandom:'RUBIES' },
  { group:'PINK LABEL', fandom:'LABELS' },
  { group:'DAZE', fandom:'DAZERS' },
  { group:'HUSH', fandom:'WHISPERS' },
  { group:'NEON PETAL', fandom:'PETALS' },
  { group:'LUMINOUS', fandom:'GLOWS' },
  { group:'ETHEREAL', fandom:'SPIRITS' },
  { group:'GARNET', fandom:'GEMS' },
  { group:'OPAL', fandom:'OPALS' },
  { group:'TWILIGHT', fandom:'DUSKS' },
  { group:'DAYBREAK', fandom:'DAWNS' },
  { group:'MERMAID', fandom:'SEASHELLS' },
  { group:'PIXIE', fandom:'SPRITES' },
  { group:'BLUSH', fandom:'FLUSHES' },
  { group:'LACE', fandom:'RIBBONS' },
  { group:'SOLEIL', fandom:'RAYS' },
  { group:'MYSTIC', fandom:'ORACLES' },
  { group:'SHIMMER', fandom:'GLIMMERS' },
  { group:'CIPHER', fandom:'CODES' },
  { group:'EMBER', fandom:'SPARKS' },
  { group:'CASCADE', fandom:'RIPPLES' },
  { group:'SERAPH', fandom:'WINGS' },
  { group:'HALO', fandom:'RINGS' },
  { group:'ECHO', fandom:'REVERBS' },
  { group:'PHANTOM', fandom:'SHADOWS' },
  { group:'AZURE', fandom:'SKIES' },
  { group:'FABLE', fandom:'STORIES' },
  { group:'NOVA', fandom:'SUPERNOVAS' },
  { group:'RIBBON', fandom:'BOWS' },
  { group:'CLOVER', fandom:'LUCKY' },
  { group:'MARBLE', fandom:'SWIRLS' },
  { group:'EMBER GLOW', fandom:'FLICKERS' },
  { group:'PRISM', fandom:'SPECTRUMS' },
  { group:'SILK', fandom:'THREADS' },
  { group:'HORIZON', fandom:'VOYAGERS' },
  { group:'LILY', fandom:'PETALS' },
  { group:'MUSE', fandom:'DREAMERS' },
  { group:'FROST', fandom:'SNOWFLAKES' },
  { group:'BLOOM', fandom:'GARDENS' },
  { group:'PULSE', fandom:'HEARTBEATS' },
  { group:'WHISPER', fandom:'ECHOES' },
  { group:'VIVID', fandom:'COLORS' },
  { group:'EDEN', fandom:'ANGELS' }
];
