// 出圈曲描述池（80条）
// 韩国女团风格歌曲，含英文/韩文混合歌名
export var HIT_SONGS = [
  '出道曲《Moonlight Letter》——中规中矩但粉丝情怀满满',
  '小爆曲《Stay With Me》——曾进音源榜前30，综艺常被点名',
  '抒情曲《Rainy Day》——被用作某韩剧OST后小范围出圈',
  '夏日曲《Sugar High》——打歌舞台点击尚可，没能破圈',
  '再出道曲《Echo》——概念反转尝试，圈内评价两极',
  '逆行神曲《First Love》——发歌半年后突然逆袭回榜',
  '电子风《Neon Sign》——夜店和短视频平台频繁使用',
  '合作曲《Starlight》——与知名制作人合作，评论说你的音色被完美展现',
  '芭蕾概念曲《Swan Song》——MV唯美到被国外YouTuber做reaction',
  '校园三部曲终章《Graduation》——毕业季必听，每年三月翻红',
  '复古Disco《Flashback》——90年代画质MV引发模仿热潮',
  '城市Pop《Seoul City Lights》——首尔夜景为背景的MV',
  '自作曲《写给粉丝的歌(Letter to {fandomName})》——粉丝名全写进歌词',
  '日文版翻唱曲——给日本粉丝的惊喜礼物',
  '中文版《星光》——发音标准中国粉丝暴哭',
  '英文单曲《Fly》——首次挑战海外市场',
  '合唱曲《双子星》——与主唱姐姐双人和声',
  'remix版团歌——重新编曲加入自己风格',
  '摇滚单曲《破茧》——爆发力嗓音惊艳',
  '民谣风《回家》——旋律温暖嗓音真挚',
  '嘻哈合作曲——首次挑战rap打破甜美形象',
  '爵士风格《深夜电台》——展示成熟另一面',
  '全英文《Butterfly Effect》——Spotify Viral 50入榜',
  '抒情曲《晚安》——深夜治愈系代表作',
  '夏日清凉《西瓜冰(Watermelon Ice)》——海边MV',
  '冬季抒情《初雪那天(First Snow)》——圣诞温暖礼物',
  'R&B《未读(Unread)》——已读不回的心跳等待',
  '电子风《霓虹(Neon)》——全新曲风挑战',
  'OST合作《名为你的诗》——网络剧主题曲',
  '传统融合《花路(Flower Road)》——韩服造型震惊全网',
  '拉丁风《Fiesta》——海外音乐节反响热烈',
  'Deep House《Dive》——夜店必放曲目',
  '独立摇滚《Rebel Heart》——首次参与作词作曲',
  '管弦乐《Overture》——演唱会同名主题曲',
  '圣诞曲《Candle Night》——每年12月都会回榜',
  '致敬前辈《Legacy》——翻唱重新编曲',
  '地铁曲《Commute》——SM STATION风格',
  '慈善曲《Together》——收益全部捐赠',
  '游戏OST《Final Boss》——电竞圈意外好评',
  '纪录片OST《镜中人》——记录练习生到出道全过程',
  'Tropical House《Island》——度假风MV',
  'Acoustic《Campfire》——不插电吉他伴奏',
  'Funk《Groove》——贝斯和铜管主导',
  'Gospel《Hallelujah》——教堂背景录制',
  'Mini专辑主打《Daydream》——白日梦概念',
  '正规专辑主打《Odyssey》——史诗感序曲',
  '先行曲《Prologue》——回归预告',
  '后续曲《Epilogue》——活动收尾',
  '特别单曲《Anniversary》——出道周年纪念曲',
  '成员合作曲《Sisters》——全团六人参与创作',
  '翻唱IU前辈《夜信》——安静吉他伴奏',
  '翻唱英文歌《Someone Like You》——情感爆发力',
  '翻唱SEVENTEEN前辈曲——同公司前后辈致敬',
  '翻唱老歌双语版——韩文原词+中文版本',
  '翻唱海外R&B金曲——全英文发音展示',
  '圣诞串烧——三首经典圣诞歌连唱',
  '独立音乐人cover——发掘宝藏好歌',
  '老牌抒情曲翻唱——重新诠释经典',
  '动画主题曲翻唱——童心满满治愈版',
  '前辈女团名曲dance cover——自唱live版',
  '抒情摇滚翻唱——爆发式高音',
  '练习生时期歌翻唱——成长史回溯',
  '粉丝投票歌——评论最高赞选定',
  '日文翻唱——流利日语展示',
  '钢琴弹唱串烧——从小弹到大的歌',
  '队友写的歌翻唱——另一种声音演绎',
  '地铁站现场版《Acoustic Live》——街头表演',
  '管弦乐改编版《Symphony Ver.》——交响乐合作',
  '不插电版《Unplugged Live》——纯吉他伴奏',
  'A Cappella版——全员和声版',
  'Band Live版——全乐队现场伴奏',
  'Remix Pack——三版本混音合集',
  'English Ver.——全英文重新录制',
  'Japanese Ver.——日本出道版',
  'Chinese Ver.——中文填词版',
  'Orchestra Ver.——与首尔爱乐合作',
  'Piano Ver.——纯钢琴弹唱',
  'Lo-fi Remix——自习室/咖啡厅专用',
  'Sped Up Ver.——短视频平台定制',
  'Slowed+Reverb——深夜情绪版'
];
