// 男主主动联络池（60条 + 每条含3选项）
// 电话/吃醋电话/私信/暗号私信/哥哥转达/哥哥试探 6类
export var CONTACT_TYPE_POOL = [].concat(
  [{cat:'call',t:'晚上十一点，你的手机响了——是他的号码。接通后他沉默了两秒才说："没什么事，就是想听听你的声音。"',minAff:30,
    options:[{t:'笑他：你好奇怪',aff:2,jealous:0},{t:'说：我也想听你的声音',aff:3,jealous:0},{t:'安静地听着他的呼吸声',aff:1,jealous:0}]},
   {cat:'call',t:'他打电话来问今天打歌顺不顺利，语气比平时轻柔，像是怕打扰又忍不住想问。',minAff:20,
    options:[{t:'说很顺利，问他怎么知道的',aff:2,jealous:0},{t:'反问他今天怎么样',aff:1,jealous:0},{t:'说其实很累，但听到你的声音好多了',aff:3,jealous:0}]},
   {cat:'call',t:'他在待机室打来的电话，背景音嘈杂但你只听见他的声音："我看到你今天的舞台了。真的很好。"',minAff:20,
    options:[{t:'问他觉得哪里最好',aff:1,jealous:0},{t:'说谢谢前辈夸奖',aff:0,jealous:1},{t:'说我自己也觉得今天状态好',aff:1,jealous:0}]},
   {cat:'call',t:'深夜，他说录音刚结束，声音有点沙哑："你还没睡？正好，有段旋律你听听看。"',minAff:35,
    options:[{t:'认真听完给意见',aff:2,jealous:0},{t:'说这旋律让我想起你',aff:3,jealous:0},{t:'问他是不是熬夜了要早点休息',aff:1,jealous:0}]},
   {cat:'call',t:'他"不小心"按到你的号码，接通后说打错了，但也没有马上挂断。',minAff:15,
    options:[{t:'拆穿他：你是故意打错的吧',aff:2,jealous:0},{t:'假装相信说没关系然后聊起来',aff:1,jealous:0},{t:'笑他说前辈也会打错电话啊',aff:1,jealous:0}]},
   {cat:'call',t:'他在洗澡前打了个电话，说只是想确认你今天没事。水声、他的声音、还有你说不出的心跳。',minAff:40,
    options:[{t:'说今天很好——因为有你打电话来',aff:3,jealous:0},{t:'问他水声好大是刚洗完吗',aff:1,jealous:0},{t:'说你现在打电话越来越随便了',aff:0,jealous:1}]},
   {cat:'call',t:'清晨六点的电话，他说刚练完舞，问你是不是也在去公司的路上。他的呼吸还没平复。',minAff:25,
    options:[{t:'心疼他这么早就在练舞',aff:2,jealous:0},{t:'说我在车上 一起吃早餐吗',aff:3,jealous:0},{t:'假装没睡醒嗯嗯应付',aff:1,jealous:0}]},
   {cat:'call',t:'你们聊了二十分钟，他说了很多工作上的事，最后轻声补了一句："其实就是找个借口听你说说话。"',minAff:40,
    options:[{t:'说那你以后不用找借口',aff:3,jealous:0},{t:'笑了然后说想听多久都可以',aff:2,jealous:0},{t:'假装没听清让他再说一遍',aff:1,jealous:1}]},
   {cat:'call',t:'电话接通后他只说了你的名字就安静了。你问他怎么了，他说"没什么，突然想叫叫你的名字"。',minAff:50,
    options:[{t:'反叫他的全名回敬',aff:2,jealous:0},{t:'安静地陪着他呼吸',aff:3,jealous:0},{t:'说你是不是喝酒了',aff:0,jealous:1}]},
   {cat:'call',t:'他打电话说在便利店看到你爱喝的香蕉牛奶，想起你上次说练习完想喝，"下次我给你带"。',minAff:25,
    options:[{t:'说我现在就想喝——你来吗',aff:3,jealous:0},{t:'说你还记得啊好感动',aff:2,jealous:0},{t:'说你不会给全队都带吧',aff:0,jealous:2}]}],
  // call_jealous 吃醋来电
  [{cat:'call_jealous',t:'他打来电话，语气比平时低："今天你待机室门口站了二十分钟的那个人——是谁。"其实是你新来的造型师。',minAff:35,
    options:[{t:'笑着解释是新造型师',aff:0,jealous:-2},{t:'反问你是不是在吃醋',aff:2,jealous:-1},{t:'说你居然数了二十分钟',aff:1,jealous:0}]},
   {cat:'call_jealous',t:'"那个后辈组合的rapper——他今天看你的眼神我不喜欢。"你愣了一下才反应过来他说的是谁。',minAff:40,
    options:[{t:'说我只看到你一个人的眼神',aff:3,jealous:-2},{t:'问你是不是一直在看我',aff:2,jealous:-1},{t:'说你想多了人家只是礼貌',aff:0,jealous:1}]},
   {cat:'call_jealous',t:'他没头没尾地打来："你发的泡泡说今天很开心——是因为什么。"',minAff:45,
    options:[{t:'说因为想到你才发的',aff:3,jealous:-2},{t:'问你是不是翻我泡泡了',aff:1,jealous:0},{t:'说每天见到你都开心',aff:2,jealous:-1}]},
   {cat:'call_jealous',t:'语音电话接通，他那边沉默了三秒："我今天在待机室看到你和{maleLead}的合照——什么时候拍的。"',minAff:42,
    options:[{t:'说是公司安排的宣传照',aff:0,jealous:0},{t:'说你怎么连合照都吃醋',aff:2,jealous:-1},{t:'问你是不是一直闷在心里',aff:2,jealous:-2}]},
   {cat:'call_jealous',t:'他半夜打来："你ins最新那条限动——跟你合影的那个男生是谁。"',minAff:38,
    options:[{t:'说是合作的化妆师',aff:0,jealous:-1},{t:'说你怎么还不睡就在刷我ins',aff:1,jealous:0},{t:'说你这么在意干嘛不直接问',aff:1,jealous:-1}]}],
  // msg 私信
  [{cat:'msg',t:'kkt消息。只有一行字："今天的舞台，副歌第二句你是不是改了。"',minAff:20,
    options:[{t:'问他怎么听得这么仔细',aff:2,jealous:0},{t:'承认改了，问他觉得怎么样',aff:1,jealous:0},{t:'回一个得意emoji不说破',aff:1,jealous:0}]},
   {cat:'msg',t:'凌晨一点，他发来一段音频文件。"刚写好的demo——想让你第一个听。"',minAff:40,
    options:[{t:'听完认认真真给反馈',aff:2,jealous:0},{t:'说这旋律让我想起那天汉江边',aff:3,jealous:0},{t:'说太好听了可以发泡泡吗',aff:1,jealous:0}]},
   {cat:'msg',t:'他发了一张照片——是你今天打歌ending镜头的截图。"存了。做壁纸了。"',minAff:45,
    options:[{t:'回他你的直拍截图说我也存了',aff:3,jealous:0},{t:'说你居然截我ending图好幼稚',aff:1,jealous:0},{t:'问他壁纸别人看到怎么办',aff:2,jealous:0}]},
   {cat:'msg',t:'他发来一张月亮照片。"今天的月亮——我觉得你应该看到了。但我想确认。"',minAff:30,
    options:[{t:'说看到了 但你的拍得更亮',aff:2,jealous:0},{t:'回他一张你拍的月亮',aff:1,jealous:0},{t:'说你是不是在阳台 风大回去穿衣服',aff:2,jealous:0}]},
   {cat:'msg',t:'他发了一段歌词截图——只有两行。"写了很久。但总觉得少了什么。现在知道了。"',minAff:48,
    options:[{t:'问少了什么',aff:1,jealous:0},{t:'说写的是不是……（没打完）',aff:2,jealous:0},{t:'假装没看懂问是写给谁的',aff:0,jealous:1}]},
   {cat:'msg',t:'练习结束后他发来一个定位——是公司旁边的便利店。"出来买水。顺便。"',minAff:22,
    options:[{t:'说马上到',aff:3,jealous:0},{t:'笑他说真会找借口',aff:1,jealous:0},{t:'说太晚了明天吧',aff:0,jealous:0}]}],
  // msg_code 暗号私信
  [{cat:'msg_code',t:'他发的消息看起来像广告文案："今晚月色很好。推荐抬头看看。"——你愣了一秒才意识到这根本不是什么广告。',minAff:50,
    options:[{t:'回他"星星也很亮"',aff:3,jealous:0},{t:'假装没看懂问什么品牌广告',aff:0,jealous:1},{t:'直接打视频过去',aff:2,jealous:0}]},
   {cat:'msg_code',t:'他发了一段韩文歌词——是你们出道曲的变调。用空格隔开每个字。拼起来是"我 在 看 你 的 直 拍"。',minAff:55,
    options:[{t:'回他变调的下一段',aff:3,jealous:0},{t:'说你是不是该写自己的歌而不是我的',aff:1,jealous:0},{t:'回一个心形emoji',aff:2,jealous:0}]},
   {cat:'msg_code',t:'他发来一张便利贴照片——上面写了一个日期和地点。是你之前说过想去看的展览。下面只有一行字：票两张。要不要。',minAff:52,
    options:[{t:'说要。哪天',aff:3,jealous:0},{t:'说两张——是跟我吗',aff:2,jealous:0},{t:'说工作太忙不确定',aff:0,jealous:0}]}],
  // brother_relay 哥哥转达
  [{cat:'brother_relay',t:'哥哥给你发消息："{maleLead}让我告诉你——录音室的咖啡他帮你留了一杯。"末了补一句"这小子不是自己能发吗"。',minAff:30,
    options:[{t:'让哥哥帮我谢谢他',aff:2,jealous:0},{t:'说他自己怎么不发',aff:1,jealous:0},{t:'回哥哥说他管太多了',aff:0,jealous:0}]},
   {cat:'brother_relay',t:'哥哥翻白眼递手机给你："他问你是不是感冒了——你怎么不回他消息？"屏幕上是{maleLead}三小时前发的kkt。',minAff:35,
    options:[{t:'接过手机自己回复',aff:3,jealous:0},{t:'说今天太忙了没看到',aff:1,jealous:0},{t:'让哥回"她睡着了"',aff:0,jealous:1}]},
   {cat:'brother_relay',t:'哥哥在待机室晃悠："{maleLead}刚录完音——让我问你要不要去听他新写的歌。他不敢自己问。"',minAff:28,
    options:[{t:'说去 现在就去',aff:3,jealous:0},{t:'让哥哥帮我带句话说很好听',aff:1,jealous:0},{t:'说让他自己跟我说',aff:0,jealous:0}]},
   {cat:'brother_relay',t:'哥哥发来截图——是{maleLead}给他的kkt："你妹妹身体不舒服？她今天脸有点白。"哥哥附言："自己不会发吗？"',minAff:32,
    options:[{t:'让哥哥说没事 就是没睡好',aff:1,jealous:0},{t:'自己给他发消息说谢谢关心',aff:3,jealous:0},{t:'笑说你们两个都很烦人',aff:0,jealous:0}]}],
  // brother_tentative 哥哥试探
  [{cat:'brother_tentative',t:'哥哥看似不经意地发消息："你觉得{maleLead}这个人怎么样。"没有表情，看不出来他是在试探还是认真的。',minAff:25,
    options:[{t:'说是我喜欢的人',aff:3,jealous:0},{t:'反问哥你觉得呢',aff:1,jealous:0},{t:'说就那样吧——一个前辈',aff:-1,jealous:2}]},
   {cat:'brother_tentative',t:'哥哥突然发来：你最近是不是经常去他练习室。我看到你每次回来的时间越来越晚。',minAff:30,
    options:[{t:'说只是在看他练舞——顺便自己练',aff:0,jealous:0},{t:'问哥你是在试探我吗',aff:1,jealous:0},{t:'承认我喜欢他 哥你要反对吗',aff:3,jealous:0}]},
   {cat:'brother_tentative',t:'哥哥丢来一张照片——是{maleLead}手机屏上你在待机室睡觉的偷拍。"他存的。你怎么想。"',minAff:45,
    options:[{t:'心里一暖但嘴上说没怎么想',aff:1,jealous:0},{t:'说那我也存过他的',aff:2,jealous:0},{t:'反问他存了多少张',aff:1,jealous:0}]}]
);
