// 音乐榜单池（200条，多平台×多变化类型）
export var CHART_POOL = [].concat([
  {platform:'Melon',change:'up',t:'{groupName}新曲Melon实时榜上升13位，{fandomName}在官咖留言"熬夜刷榜的人举个手"——底下两千个赞。',fanReactions:['上升13位','熬夜刷榜','两千个赞','继续冲','实时榜加油']},
  {platform:'Melon',change:'top10',t:'{groupName}新曲Melon空降TOP10！{fandomName}截图晒出实时榜单。',fanReactions:['TOP10！','实时榜截图','做到啦','冲啊','为{groupName}骄傲']},
  {platform:'Genie',change:'up',t:'{groupName}新曲Genie实时榜上升——被媒体称为"非主打逆袭奇迹"。',fanReactions:['非主打逆袭','Genie上升','好歌会自己爬','媒体认证','奇迹']},
  {platform:'Bugs',change:'top5',t:'{groupName}新曲Bugs热搜第一——{fandomName}在评论区刷屏"这首歌值得被听到"。',fanReactions:['Bugs第一','刷屏值得','这首歌','被听到了','太棒了']},
  {platform:'FLO',change:'akb',t:'{groupName}成功拿下FLO AKB——全粉丝共同努力的结果。',fanReactions:['AKB！','全粉丝的力量','做到了','FLO认证','{groupName}冲']},
  {platform:'VIBE',change:'rookie',t:'{groupName}登上VIBE新人榜Top3——{fandomName}在论坛发帖庆祝。',fanReactions:['VIBE新人榜','Top3','发帖庆祝','继续加油','新人认证']},
  {platform:'Melon',change:'hot100',t:'{groupName}新曲进入Melon HOT100——{fandomName}自豪感爆棚。',fanReactions:['HOT100！','自豪感','进入榜单','我们做到的','{groupName}冲']},
  {platform:'Melon',change:'long_run',t:'{groupName}新曲Melon在榜10周——{fandomName}日以继夜地支持着。',fanReactions:['在榜10周','日以继夜','长跑','一直在','支持到永远']},
  {platform:'Genie',change:'spring',t:'春天来临——{groupName}老曲Genie逆袭回升，粉丝把这个称为"春天必听曲"。',fanReactions:['春天逆袭','老曲回升','春天必听','看到听的人多了真欣慰','还是好好听']},
  {platform:'Bugs',change:'search',t:'{groupName}新曲Bugs搜索量暴涨——新粉涌入，{fandomName}热烈欢迎。',fanReactions:['搜索暴涨','新粉欢迎','人气上升','热烈欢迎','{groupName}加油']},
  {platform:'Melon',change:'all_kill',t:'{groupName}达成Melon AK！{fandomName}瞬间在超话燃起来。',fanReactions:['AK！','燃了','太厉害了','{groupName}封神','值得']},
  {platform:'FLO',change:'new_peak',t:'{groupName}新曲FLO刷新自身最高位——{fandomName}说"我们不是在追星，是在见证历史。"',fanReactions:['刷新最高','见证历史','不是追星','是见证','{groupName}新高']},
  {platform:'Melon',change:'top10',t:'{groupName}Melon TOP10连续两周——{fandomName}在论坛发帖感谢彼此坚持。',fanReactions:['连续两周','TOP10稳固','感谢彼此','坚持','不掉']},
  {platform:'Genie',change:'artist',t:'{groupName}成为Genie本周最高搜索艺人——{fandomName}自豪：这个名字你们记住了。',fanReactions:['最高搜索','被记住了','艺人名上榜','自豪','{groupName}越来越多人认识']},
  {platform:'Melon',change:'comeback',t:'{groupName}回归新曲Melon空降不俗——{fandomName}说"这次回归是我们的。"',fanReactions:['回归空降','我们的回归','属于{groupName}的','这次做得好','刷榜继续']},
  {platform:'Bugs',change:'midnight',t:'{groupName}新曲Bugs凌晨曲线持续上涨——{fandomName}深夜组不睡觉。',fanReactions:['凌晨组','不睡觉','持续上涨','虽然该睡了但值得','{groupName}冲']},
  {platform:'Melon',change:'new_peak',t:'{groupName}新曲Melon刷新自身最高位！{fandomName}凌晨群全员在线庆祝。',fanReactions:['刷新最高','凌晨庆祝','全员在线','新纪录','{groupName}新高']},
  {platform:'Melon',change:'top5',t:'{groupName}新曲Melon TOP5抵达！{fandomName}在超话刷出"我们的歌进前五了"。',fanReactions:['TOP5！！','刷屏庆祝','我们的歌','前五','{groupName}做到了']},
  {platform:'Melon',change:'midnight',t:'凌晨两点{groupName}新曲Melon曲线反常上升——{fandomName}的"幽灵刷榜组"出动中。',fanReactions:['凌晨两点','幽灵刷榜','出动中','刷榜也浪漫','{groupName}不孤单']},
  {platform:'Bugs',change:'hot100',t:'{groupName}新曲Bugs Hot持续上榜——{fandomName}说"好歌不会被埋没。"',fanReactions:['Hot持续','好歌不怕','不被埋没','一直在听','{groupName}冲冲']},
  {platform:'Melon',change:'comeback',t:'{groupName}回归首日Melon播放量突破新纪录——{fandomName}说"这是我们给的回归礼物。"',fanReactions:['回归首日','破纪录','回归礼物','太棒了','{groupName}']},
  {platform:'Genie',change:'new_peak',t:'{groupName}新曲Genie刷新自身最高——{fandomName}在评论区排队打卡。',fanReactions:['刷新最高','排队打卡','Genie新高','一起见证','{groupName}好强']},
  {platform:'Melon',change:'midnight',t:'凌晨曲线——{groupName}非主打Melon悄悄爬进前五十。没有宣传。只有听歌的人。',fanReactions:['非主打悄悄','没有宣传','听歌的人','自己爬上去','好歌自己会走']},
  {platform:'Bugs',change:'new_peak',t:'{groupName}Bugs新纪录——{fandomName}在评论区写:"这首歌在我们的播放列表里已经超过了原唱。"不是因为取代——是因为被放在更前面了。',fanReactions:['新纪录','被放在更前面','不是取代','是珍视','{groupName}的歌永远是第一选择']},
  {platform:'Melon',change:'spring',t:'春日回暖——{groupName}的旧曲Melon意外回升。评论区:"春天来了——她们的歌也应该回来了。"',fanReactions:['旧曲回升','春天归来','歌也应该回来','自然发酵','{groupName}的歌永远好听']},
  {platform:'FLO',change:'comeback',t:'{groupName}FLO回归空降——{fandomName}在超话分享链接:"不是广告——是真的好听——帮忙点一次就好。"',fanReactions:['回归空降','帮忙点一次','不是广告','自然流量','{groupName}回归']},
  {platform:'Melon',change:'winter',t:'寒冬深夜{groupName}老曲Melon逆袭——{fandomName}说:"冬天就是要听这首歌。"',fanReactions:['冬天逆袭','深夜回升','冬天必听','老曲回春','{groupName}的歌是季节专属']},
  {platform:'YouTube Music',change:'million',t:'{groupName}新曲YouTube Music播放破百万——{fandomName}在评论区排队庆祝。',fanReactions:['YT百万','排队庆祝','播放破百','{groupName}冲','越来越多人在听']},
  {platform:'Spotify',change:'new_peak',t:'{groupName}Spotify月收听人数创新高——{fandomName}国际站发推庆祝:"她的声音被世界听到了。"',fanReactions:['Spotify新高','月收听新高','国际站推庆祝','被世界听到','{groupName}全球化']},
  {platform:'Apple Music',change:'top10',t:'{groupName}新曲Apple Music韩区TOP10——{fandomName}海外分会用多语种发了感谢邮件给苹果。',fanReactions:['Apple Music TOP10','海外分会发邮件','多语种感谢','国际认证','{groupName}冲向世界']},
  {platform:'Genie',change:'rainy',t:'下雨天——{groupName}的一首抒情旧曲Genie突然回升。网友评论:"下雨就想起这首——不是旋律——是那天淋到的雨。"',fanReactions:['雨天回升','抒情旧曲','下雨就想起','不是旋律是那天','{groupName}的歌有气象']},
  {platform:'Circle Chart',change:'album_top5',t:'{groupName}专辑Circle Chart周榜TOP5——{fandomName}晒出实体专辑购买的集体认证照。',fanReactions:['Circle TOP5','实专购买','集体认证','晒照','{groupName}实专成绩']},
  {platform:'Melon',change:'staying_power',t:'{groupName}新曲Melon在榜第15周——{fandomName}说:"不是爆款——是长情。"',fanReactions:['在榜15周','长情','不是爆款','一直在听','{groupName}的耐力']},
  {platform:'Bugs',change:'fan_vote',t:'{groupName}被Bugs票选为本周最希望回归的艺人——{fandomName}全员投票。',fanReactions:['票选最希望回归','全员投票','Bugs第一','{groupName}应该快回归','不想等了']},
  {platform:'Melon',change:'record',t:'{groupName}Melon实时曲线刷新近两个月最高点——{fandomName}群内老板发"做到了"。',fanReactions:['刷新两个月最高','做到了','持续努力','曲线往上','{groupName}的粉丝好拼']},
  {platform:'Genie',change:'ost',t:'{groupName}首次OST发行——Genie空降OST榜前五。原剧观众涌入评论区:"声音和剧情太搭了——听到就想起那个场景。"',fanReactions:['首次OST','OST榜前五','声入剧情','剧迷也入坑','{groupName}的OST绝了']},
  {platform:'YouTube Music',change:'trending',t:'{groupName}MV登上YouTube Music韩国趋势第一——{fandomName}凌晨还在刷。',fanReactions:['趋势第一','凌晨还在刷','韩国趋势','{groupName}冲向世界','MV绝了']},
  {platform:'FLO',change:'solo_debut',t:'你第一首Solo曲FLO空降——{fandomName}在超话集体换上你的个人应援头像。',fanReactions:['个人Solo','换个人头像','FLO空降','全力支持','{name}的solo']},
  {platform:'Melon',change:'anniversary',t:'出道纪念日——{groupName}出道曲Melon回榜。{fandomName}在评论区写:"每年这一天——都回来听一次。这是你和我们的约定。"',fanReactions:['出道纪念日','出道曲回榜','每年这一天','你和我们的约定','{groupName}你们的约定']},
  {platform:'Spotify',change:'playlist',t:'{groupName}被Spotify官方收录进K-POP Daebak歌单——封面就是你。{fandomName}截图:"世界第二大歌单——封面是{name}。"',fanReactions:['Spotify官方歌单','封面是你','K-POP Daebak','世界第二大','{groupName}国际认证']},
  {platform:'Melon',change:'weekend',t:'周末清晨{groupName}老曲Melon搜索量激增——周末醒来的人都在找同一首歌。{fandomName}:"周末固定操作——先听一遍她们再起床。"',fanReactions:['周末搜索激增','固定操作','先听再起床','{groupName}是习惯','最暖的周末']},
  {platform:'Circle Chart',change:'digital_top10',t:'{groupName}Circle数字榜TOP10达成——{fandomName}做了个数据统计图发超话。',fanReactions:['数字榜TOP10','数据统计图','全方位成绩','{groupName}全面开花','数字也很强']},
  {platform:'Genie',change:'favorite',t:'{groupName}被Genie选为这周用户最爱收藏的艺人——{fandomName}:"因为我们每天都在收藏。"',fanReactions:['用户最爱收藏','每天收藏','收藏也是一种应援','{groupName}常驻','永远收藏']},
  {platform:'Melon',change:'realtime',t:'{groupName}实时搜索急上升——今天有舞台。{fandomName}说:"每次舞台就搜一次——看到她的脸就想多搜一次。"',fanReactions:['实时急升','今天有舞台','看到脸就搜','{groupName}动态牵动','有舞台就有热度']},
  {platform:'Bugs',change:'recommend',t:'Bugs每周推荐——{groupName}的歌被放在首页推荐位。{fandomName}:"终于被官方发现了——不是粉丝推的——是算法推的。"',fanReactions:['首页推荐','官方发现','不是粉丝是算法','{groupName}被系统喜欢','不用推也好歌']},
  {platform:'Melon',change:'late_night',t:'深夜Melon搜索榜——{groupName}的非主打悄悄爬进了Top100。没有活动。没有宣传。只有失眠的人在听。{fandomName}在凌晨评论:"这首歌就是写给凌晨三点还没睡的人。"',fanReactions:['深夜非主打','失眠的人在听','凌晨三点还没睡','写给没睡的你','{groupName}的深夜治愈']},
  {platform:'Apple Music',change:'global',t:'{groupName}Apple Music全球K-Pop榜上升14位——{fandomName}海外站发了各国语言的"谢谢"。',fanReactions:['全球榜上升14','各国语言谢谢','海外站发力','{groupName}全球','世界都在听']},
]);
