// 音乐榜单池（200条，多平台×多变化类型）
export var CHART_POOL = [].concat([
  {platform:'Melon',change:'up',t:'{groupName}新曲Melon实时榜上升13位，{fandomName}在官咖留言"熬夜刷榜的人举个手"——底下两千个赞。',fanReactions:['上升13位','熬夜刷榜','两千个赞','继续冲','实时榜加油']},
  {platform:'Melon',change:'top10',t:'{groupName}新曲Melon空降TOP10！{fandomName}截图晒出实时榜单。',fanReactions:['TOP10！','实时榜截图','做到啦','冲啊','为{groupName}骄傲']},
  {platform:'Genie',change:'up',t:'{groupName}新曲Genie实时榜上升——被媒体称为"非主打逆袭奇迹"。',fanReactions:['非主打逆袭','Genie上升','好歌会自己爬','媒体认证','奇迹']},
  {platform:'Bugs',change:'top5',t:'{groupName}新曲Bugs热搜第一——{fandomName}在评论区刷屏"这首歌值得被听到"。',fanReactions:['Bugs第一','刷屏值得','这首歌','被听到了','太棒了']},
  {platform:'FLO',change:'akb',t:'{groupName}成功拿下FLO AKB——全粉丝共同努力的结果。',fanReactions:['AKB！','全粉丝的力量','做到了','FLO认证','{groupName}冲']},
  {platform:'VIBE',change:'rookie',t:'{groupName}登上VIBE新人榜Top3——{fandomName}在论坛发帖庆祝。',fanReactions:['VIBE新人榜','Top3','发帖庆祝','继续加油','新人认证']},
  {platform:'Melon',change:'hot100',t:'{groupName}新曲进入Melon HOT100——{fandomName}自豪感爆棚。',fanReactions:['HOT100！','自豪感','进入榜单','我们做到的','{groupName}冲']},
  {platform:'Melon',change:'long_run',t:'{groupName}新曲Melon在榜10周——{fandomName}日以继夜地支持着。',fanReactions:['在榜10周','日以继夜','长跑','一直在','支持到永远']},
  {platform:'Genie',change:'spring',t:'春天来临——{groupName}老曲Genie逆袭回升，粉丝把这个称为"春天必听曲"。',fanReactions:['春天逆袭','老曲回升','春天必听','看到听的人多了真欣慰','还是好好听']},
  {platform:'Bugs',change:'search',t:'{groupName}新曲Bugs搜索量暴涨——新粉涌入，{fandomName}热烈欢迎。',fanReactions:['搜索暴涨','新粉欢迎','人气上升','热烈欢迎','{groupName}加油']},
  {platform:'Melon',change:'all_kill',t:'{groupName}达成Melon AK！{fandomName}瞬间在超话燃起来。',fanReactions:['AK！','燃了','太厉害了','{groupName}封神','值得']},
  {platform:'FLO',change:'new_peak',t:'{groupName}新曲FLO刷新自身最高位——{fandomName}说"我们不是在追星，是在见证历史。"',fanReactions:['刷新最高','见证历史','不是追星','是见证','{groupName}新高']},
  {platform:'Melon',change:'top10',t:'{groupName}Melon TOP10连续两周——{fandomName}在论坛发帖感谢彼此坚持。',fanReactions:['连续两周','TOP10稳固','感谢彼此','坚持','不掉']},
  {platform:'Genie',change:'artist',t:'{groupName}成为Genie本周最高搜索艺人——{fandomName}自豪：这个名字你们记住了。',fanReactions:['最高搜索','被记住了','艺人名上榜','自豪','{groupName}越来越多人认识']},
  {platform:'Melon',change:'comeback',t:'{groupName}回归新曲Melon空降不俗——{fandomName}说"这次回归是我们的。"',fanReactions:['回归空降','我们的回归','属于{groupName}的','这次做得好','刷榜继续']},
  {platform:'Bugs',change:'midnight',t:'{groupName}新曲Bugs凌晨曲线持续上涨——{fandomName}深夜组不睡觉。',fanReactions:['凌晨组','不睡觉','持续上涨','虽然该睡了但值得','{groupName}冲']},
  {platform:'Melon',change:'new_peak',t:'{groupName}新曲Melon刷新自身最高位！{fandomName}凌晨群全员在线庆祝。',fanReactions:['刷新最高','凌晨庆祝','全员在线','新纪录','{groupName}新高']},
  {platform:'Melon',change:'top5',t:'{groupName}新曲Melon TOP5抵达！{fandomName}在超话刷出"我们的歌进前五了"。',fanReactions:['TOP5！！','刷屏庆祝','我们的歌','前五','{groupName}做到了']},
  {platform:'Melon',change:'midnight',t:'凌晨两点{groupName}新曲Melon曲线反常上升——{fandomName}的"幽灵刷榜组"出动中。',fanReactions:['凌晨两点','幽灵刷榜','出动中','刷榜也浪漫','{groupName}不孤单']},
  {platform:'Bugs',change:'hot100',t:'{groupName}新曲Bugs Hot持续上榜——{fandomName}说"好歌不会被埋没。"',fanReactions:['Hot持续','好歌不怕','不被埋没','一直在听','{groupName}冲冲']},
  {platform:'Melon',change:'comeback',t:'{groupName}回归首日Melon播放量突破新纪录——{fandomName}说"这是我们给的回归礼物。"',fanReactions:['回归首日','破纪录','回归礼物','太棒了','{groupName}']},
  {platform:'Genie',change:'new_peak',t:'{groupName}新曲Genie刷新自身最高——{fandomName}在评论区排队打卡。',fanReactions:['刷新最高','排队打卡','Genie新高','一起见证','{groupName}好强']},
  {platform:'Melon',change:'midnight',t:'凌晨曲线——{groupName}非主打Melon悄悄爬进前五十。没有宣传。只有听歌的人。',fanReactions:['非主打悄悄','没有宣传','听歌的人','自己爬上去','好歌自己会走']},
  {platform:'Bugs',change:'new_peak',t:'{groupName}Bugs新纪录——{fandomName}在评论区写:"这首歌在我们的播放列表里已经超过了原唱。"不是因为取代——是因为被放在更前面了。',fanReactions:['新纪录','被放在更前面','不是取代','是珍视','{groupName}的歌永远是第一选择']},
  {platform:'Melon',change:'spring',t:'春日回暖——{groupName}的旧曲Melon意外回升。评论区:"春天来了——她们的歌也应该回来了。"',fanReactions:['旧曲回升','春天归来','歌也应该回来','自然发酵','{groupName}的歌永远好听']},
  {platform:'FLO',change:'comeback',t:'{groupName}FLO回归空降——{fandomName}在超话分享链接:"不是广告——是真的好听——帮忙点一次就好。"',fanReactions:['回归空降','帮忙点一次','不是广告','自然流量','{groupName}回归']},
]);
