// 队友角色定位模板（30条组合）
// 女主固定：忙内(Maknae)+门面(Visual)+副主唱(Lead Vocal)
// 5位姐姐按模板拼装
export var SISTER_ROLES = [
  { roles:['队长/主唱','主舞/C位','Rapper','领唱/综艺担当','领舞/气氛担当'], size:6 },
  { roles:['队长/主唱','主舞','主Rapper','门面/副唱','综艺担当'], size:6 },
  { roles:['主唱(最强vocal)','队长/领舞','主Rapper','领唱','忙内line'], size:6 },
  { roles:['队长/主Rapper','主唱','主舞','领唱/综艺','领舞'], size:6 },
  { roles:['主唱(情感担当)','主舞/队长','Rapper/制作人','领唱/门面','领舞/忙内line'], size:6 },
  { roles:['队长/领唱','主唱','主舞','主Rapper','综艺/气氛'], size:5 },
  { roles:['主唱','队长/领舞','Rapper','领唱/综艺'], size:5 },
  { roles:['主唱/队长','主舞','Rapper/门面','领唱'], size:5 },
  { roles:['主唱','主舞/队长','主Rapper','领唱/忙内line'], size:5 },
  { roles:['队长/主唱','主舞','主Rapper','领唱/门面'], size:5 },
  { roles:['主唱(高音担当)','主舞/队长','Rapper/制作','领唱/综艺','领舞/门面','忙内line'], size:7 },
  { roles:['队长/主唱','主舞','主Rapper','领唱','领舞','门面/忙内line'], size:7 },
  { roles:['主唱','队长/领舞','主Rapper','领唱/综艺','门面','忙内line'], size:7 },
  { roles:['主唱/队长','主舞','Rapper','门面/副唱'], size:5 },
  { roles:['主唱','队长/领舞','主Rapper','领唱'], size:5 },
  { roles:['主唱','主舞','Rapper/队长','领唱/门面','综艺'], size:6 },
  { roles:['队长/主唱','主舞','Rapper','门面','综艺'], size:6 },
  { roles:['主唱','主舞/队长','Rapper/门面','领唱/综艺'], size:5 },
  { roles:['队长/主Rapper','主唱','主舞','副唱','门面'], size:6 },
  { roles:['主唱/队长','主舞/副唱','Rapper','领唱/综艺'], size:5 },
  { roles:['队长/主唱','主舞','Rapper','门面/综艺','领舞'], size:6 },
  { roles:['主唱(OST女王)','队长/领舞','主Rapper','领唱/门面','综艺'], size:6 },
  { roles:['主唱','主舞','Rapper/队长','门面','领舞'], size:6 },
  { roles:['队长/主唱','领唱/主舞','主Rapper','门面','综艺'], size:6 },
  { roles:['主唱/队长','主舞','Rapper','综艺/门面'], size:5 },
  { roles:['主唱','主舞','队长/Rapper','门面','综艺/气氛'], size:6 },
  { roles:['主唱(实力派)','主舞/队长','主Rapper','门面/领唱','忙内line/领舞'], size:6 },
  { roles:['队长/主唱','主舞/门面','主Rapper','领唱/综艺'], size:5 },
  { roles:['主唱','队长/主舞','Rapper/制作','门面/综艺'], size:5 },
  { roles:['主唱(高音)','主舞','Rapper/队长','门面','领舞/综艺'], size:6 }
];
