// trainee-chat.js | 练习生聊天池 | 哥哥鼓励30条+情敌暗自较劲30条 | 60条
export var TRAINEE_CHAT = [].concat(
  // 哥哥频道（练习生期鼓励/关心）30条
  [
    { ch: 'brother', t: '今天月末评价怎么样？别太紧张，尽力就好。', require: 'trainee' },
    { ch: 'brother', t: '练到几点？别太晚了，明天还有课。', require: 'trainee' },
    { ch: 'brother', t: '我路过你们练习室，看你跳得不错啊。', require: 'trainee' },
    { ch: 'brother', t: '吃了没？我在你们公司附近，要不要我带点东西过来？', require: 'trainee' },
    { ch: 'brother', t: '听说你今天被老师夸了？可以的。', require: 'trainee' },
    { ch: 'brother', t: '腿还疼吗？上次看到你走路一瘸一拐的。', require: 'trainee' },
    { ch: 'brother', t: '月末评价的事情别想太多，一次拿C不代表什么。', require: 'trainee' },
    { ch: 'brother', t: '我出道前也被刷过两次，真的没什么。', require: 'trainee' },
    { ch: 'brother', t: '你们那个出道组的消息……我打听到了，你想听吗？', require: 'trainee' },
    { ch: 'brother', t: '妈让我问你最近有没有好好吃饭。', require: 'trainee' },
    { ch: 'brother', t: '我队友说昨天在走廊看到你了，说你瘦了好多。', require: 'trainee' },
    { ch: 'brother', t: '今天行程结束得早，要不要来我们公司食堂？请你吃好的。', require: 'trainee' },
    { ch: 'brother', t: '你那个编舞我看过，有几个地方可以改一下——你要不要听听？', require: 'trainee' },
    { ch: 'brother', t: '综艺课别偷懒，出道以后这个比唱歌跳舞还重要。', require: 'trainee' },
    { ch: 'brother', t: '今天心情不好？看你发的表情包就知道了。', require: 'trainee' },
    { ch: 'brother', t: '刚跟你们经纪人聊了几句，他说你进步很快。', require: 'trainee' },
    { ch: 'brother', t: '别跟那个谁较劲了，你们风格不一样。', require: 'trainee' },
    { ch: 'brother', t: '出道以后你会发现现在担心的事情都不是事儿。', require: 'trainee' },
    { ch: 'brother', t: '我今天录音到凌晨，看到你们练习室的灯还亮着——你是不是又最后一个走？', require: 'trainee' },
    { ch: 'brother', t: '给你寄了一箱运动饮料，放在前台了。', require: 'trainee' },
    { ch: 'brother', t: '你觉得你现在最需要补什么？声乐还是舞蹈？我帮你问问有没有好的老师。', require: 'trainee' },
    { ch: 'brother', t: '周末回不回家？妈说好久没看到你了。', require: 'trainee' },
    { ch: 'brother', t: '别给自己太大压力，你已经比同期很多人好了。', require: 'trainee' },
    { ch: 'brother', t: '今天看到你的考核视频了——说实话比我想象的好很多。', require: 'trainee' },
    { ch: 'brother', t: '出道的事情顺其自然。不管结果怎么样，你已经做得很好了。', require: 'trainee' },
    { ch: 'brother', t: '我队里有个人今天问起你了——你别管他是谁。', require: 'trainee' },
    { ch: 'brother', t: '你上次问我那个声乐技巧我帮你问了我们的主唱，他说……', require: 'trainee' },
    { ch: 'brother', t: '脚踝还疼吗？我带了膏药，放你们练习室柜子上了。', require: 'trainee' },
    { ch: 'brother', t: '今天你生日——虽然你可能在练习，但我已经帮你订了蛋糕了。', require: 'trainee' },
    { ch: 'brother', t: '马上要最终考核了吧？别紧张，我出道的时候紧张到差点把话筒扔了。', require: 'trainee' }
  ],
  // 情敌频道（练习生期暗自较量）30条
  [
    { ch: 'rival', t: '听说这次的出道组只有五个名额。你觉得你有把握吗？', require: 'trainee' },
    { ch: 'rival', t: '今天那个编舞你学得挺快的——练了很久吧？', require: 'trainee' },
    { ch: 'rival', t: '我刚才看到你哥哥来了。他经常来看你吗？', require: 'trainee' },
    { ch: 'rival', t: '上次月末评价你拿了B+，进步很快啊。下次我们看看谁更高。', require: 'trainee' },
    { ch: 'rival', t: '你每天练到几点走？我好像每次走的时候你还在。', require: 'trainee' },
    { ch: 'rival', t: '听说有人在传你可能是主唱位。恭喜。', require: 'trainee' },
    { ch: 'rival', t: '你那个高音的处理方式——是老师教的还是你自己想的？', require: 'trainee' },
    { ch: 'rival', t: '今天的考核你觉得你发挥得怎么样？', require: 'trainee' },
    { ch: 'rival', t: '我听说制作人跟社长提了你的名字。厉害。', require: 'trainee' },
    { ch: 'rival', t: '出道曲demo你听过了吗？副歌部分我觉得你可能会唱得很好。', require: 'trainee' },
    { ch: 'rival', t: '你的音色真的很特别。说实话，我有点羡慕。', require: 'trainee' },
    { ch: 'rival', t: '周末我留下来了——看到你也在。要不要一起练？', require: 'trainee' },
    { ch: 'rival', t: '你哥哥是SEVENTEEN的吧？有时候在想出道的好处是不是可以离他们近一点。', require: 'trainee' },
    { ch: 'rival', t: '我今天被老师单独谈话了。说我的舞蹈需要加强——你呢？', require: 'trainee' },
    { ch: 'rival', t: '你们组今天的团练怎么样？我们组吵了一架。', require: 'trainee' },
    { ch: 'rival', t: '你觉得最终名单什么时候会出来？', require: 'trainee' },
    { ch: 'rival', t: '你外表条件太好了。这一点我确实比不过。', require: 'trainee' },
    { ch: 'rival', t: '如果出道组只有你进了而我被刷了——你会记得我吗？', require: 'trainee' },
    { ch: 'rival', t: '我今天在教学楼顶楼坐了很久。你别告诉别人。', require: 'trainee' },
    { ch: 'rival', t: '你觉得当练习生最累的是什么？不是训练——是不知道能不能出道。', require: 'trainee' },
    { ch: 'rival', t: '有人说社长很喜欢你。你觉得这是好事还是坏事？', require: 'trainee' },
    { ch: 'rival', t: '你的音域比我的宽。这一点我没办法跟你争。', require: 'trainee' },
    { ch: 'rival', t: '听说最终考核的内容改了。你有收到消息吗？', require: 'trainee' },
    { ch: 'rival', t: '我昨天梦到出道了。醒来以后发现闹钟还没响，才凌晨四点。', require: 'trainee' },
    { ch: 'rival', t: '你觉得我们算朋友还是竞争对手？', require: 'trainee' },
    { ch: 'rival', t: '如果你出道了，你最想跟哪个前辈同台？', require: 'trainee' },
    { ch: 'rival', t: '最近压力有点大——不是跟你比，是自己跟自己较劲。', require: 'trainee' },
    { ch: 'rival', t: '食堂夜宵的泡菜炒饭其实还不错。你有试过吗？', require: 'trainee' },
    { ch: 'rival', t: '出道以后我们还会这样聊天吗？', require: 'trainee' },
    { ch: 'rival', t: '不管最后谁出道——答应我别忘记现在拼命的自己。', require: 'trainee' }
  ]
);
