name = "seventeen-transfer-auth"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "e582283885ef4302b7811e7753ae3924"

[vars]
ADMIN_KEY = "svt-admin-9f3a7c2e1b8d4f60"
